# Generated by Django 4.1.7 on 2023-03-07 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HotelGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room', models.IntegerField()),
                ('entrance_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('name_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationlist')),
            ],
        ),
    ]
