# Generated by Django 4.1.7 on 2023-03-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelguest',
            name='name_list',
        ),
        migrations.DeleteModel(
            name='ReservationList',
        ),
    ]
