# Generated by Django 4.1.7 on 2023-03-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_hotelguest_name_list_delete_reservationlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotelguest',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationlist'),
        ),
    ]
