# Generated by Django 4.1.7 on 2023-03-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationlist_hotelguest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelguest',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='reservation.reservationlist'),
        ),
    ]
